### PR TITLE
Add gif to README

### PR DESCRIPTION
**Pull request by kotfic**
I tried external hosting of gif but kept running into content-length issues from github's image proxy [camo](https://github.com/atmos/camo)

### CODE REVIEW

**Comment by dorukozturk** [comment]
+1

**Comment by aashish24** [comment]
@kotfic I like the idea  but the file size it too big (12.4 MB) is that correct? I think it will slow down the process of cloning the repository. Let's try to figure out another way.

**Comment by kotfic** [comment]
@aashish24 I tried external hosting of gif but kept running into content-length issues from github's image proxy camo

I have already scaled down the image and the quality. The only other option would be to demonstrate less features

**Comment by aashish24** [comment]
Thanks @kotfic okay if we discuss it further before we merge it if this is not needed right now? Other ideas could to host it on demo.kitware.com or someplace else.

**Comment by kotfic** [comment]
externally hosting the gif will not work.

**Comment by aashish24** [comment]
I meant hosting the gif on the data.kitware.com and have a link to the page from the README. So when the users visit the data.kitware.com/geonotebook (or something similar) they will see the gif running there. Would that not work?

**Comment by kotfic** [comment]
the goal is to provide a gif on the readme so people get an immediate idea of what the software does.  Asking them to go elsewhere defeats the point. Besides,  the gif is already hosted [elsewhere](http://i.imgur.com/nx87zpq.gif). The issue is in-lining

**Comment by kotfic** [comment]
I have made a new gif that just shows off data subsetting,  it is just under 5Mb and so i am hosting it on data.kitware.com.  I will also move the other screenshots over so we aren't keeping static resources in the repo.

**Comment by jbeezley** [comment]
You should revert the first two commits so they don't get stored in the repo.

**Comment by aashish24** [comment]
LGTM 👍

**Comment by aashish24** [comment]
> You should revert the first two commits so they don't get stored in the repo.

+1 I should have been more specific about my review. I only reviewed the content (diff).

**Pull request merged**
