### PR TITLE
Raster data collections

### PR DESCRIPTION
**Pull request by kotfic**
@dorukozturk PTAL - There is a TIme Series.ipynb notebook that should let you test the functionality.  You just need the NBAR data converted to GeoTIFFs and to change the DATA_DIR variable in cell 3.

### CODE REVIEW

**Comment by dorukozturk** [comment]
@kotfic LGTM! I love the prev() and next(). One thing is, I think next should go to the beginning of the list when it reaches the end. Same with prev.
NBAR = [img_1, img_2, img_3]
x = NBAR[0]
x.next() = img_2
x.next() = img_3
x.next() = img_1

**Comment by jbeezley** [comment]
I think it would be better to keep it like a standard iterator if you are using the `.next` method.  That is, it should raise a `StopIteration` when it reaches the end.  This way you can use it anywhere else an iterator is allowed.

**Comment by dorukozturk** [comment]
@jbeezley You are right. It makes sense now.

**Comment by kotfic** [comment]
@dorukozturk PTAL, thanks!

**Comment by dorukozturk** [comment]
LGTM! 
I always forget to do vagrant up and it would be great if geoserver is not up and running an error is raised about geoserver.

**Pull request merged**
