### PR TITLE
Add screenshot provenance to notebooks

### PR DESCRIPTION
**Pull request by danlamanna**
Not sure if provenance is really the right word for it, but here it is.

Right now it's using a base64 image of a cat, but the logic is the same and will be replaced with a call to `Map.screenshot` when https://github.com/OpenGeoscience/geojs/pull/665 is merged.

This essentially adds a screenshot of the map (hidden to the user) to the Jupyter notebook output each time a python cell is executed. The screenshot is stored in the `.ipynb` file which means that when an export to other formats (such as static HTML) is performed, the user can see step by step what happened to the GeoJS map as python commands were executed.

The only really hacky part about this (besides using `_.wrap`) is that we have to hide all PNG output by default with css to avoid our screenshot PNGs flashing on the screen for a second when the user loads the notebook. This means we have to "unhide" the other PNGs when they're rendered (and on load). 

Integration test forthcoming.

### CODE REVIEW

**Comment by aashish24** [comment]
@danlamanna are we expecting more code to be pushed onto this branch? Or is this ready for review. Perhaps you have to update it with master?

**Comment by danlamanna** [comment]
@aashish24 More code will be pushed to this branch

**Comment by aashish24** [comment]
> @aashish24 More code will be pushed to this branch

ok thanks.

**Comment by danlamanna** [comment]
This has now been drastically scaled back due to issues with the asynchronous nature of the notebook. There's now a button to take screenshots which will be displayed (only when on a code cell) and endure exports to various formats. @kotfic

**Pull request merged**
