### PR TITLE
Convert Dockerfile to be based on Debian Jessie

### PR DESCRIPTION
**Pull request by danlamanna**

### CODE REVIEW

**Comment by danlamanna** [comment]
I should note the relevant issue within Jupyter that requires us to run the notebook through a shell script: https://github.com/ipython/ipykernel/pull/233

**Comment by aashish24** [comment]
thanks @danlamanna I will give it a try soon.

**Comment by dorukozturk** [comment]
@danlamanna This worked for me

**Comment by aashish24** [comment]
@danlamanna I did not see this message as mentioned in the document (https://github.com/OpenGeoscience/geonotebook/tree/master/devops/docker) but it is possible that I may have missed something. 


[C 20:30:42.834 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=4a4fe605780711fb0aea99b55836142c95af157277ac25d5

**Comment by danlamanna** [comment]
That was supposed to be disabled for Docker builds, I'll update the docs.

**Comment by aashish24** [comment]
> That was supposed to be disabled for Docker builds, I'll update the docs.

Great, thanks.

**Comment by aashish24** [comment]
LGTM +2 thanks for updating the docs.

**Pull request merged**
