### PR TITLE
Add vector layers

### PR DESCRIPTION
**Pull request by jbeezley**
This should be ready for review.  The layer constructor uses fiona to extract the dataset as geojson.  There is also a basic ability to color the features added to the layer.  The integration test examples should give an idea for how to use it.  Once we finalize on an interface we should work on some documentation.

### CODE REVIEW

**Comment by aashish24** [comment]
Awesome.. will be glad to checkout it and post my results.

**Comment by kotfic** [comment]
Looks like annotations are displaying below the vector layer?

**Comment by kotfic** [comment]
```python
next(M.layers.annotation.rectangles[0].data)
```
GIves me:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-9-824a6b7e6d90> in <module>()
----> 1 next(M.layers.annotation.rectangles[0].data)

/home/kotfic/kitware/review/geonotebook/vector-dataset/geonotebook/annotations.py in data(self)
     55         for layer in self._get_layer_collection():
     56             if hasattr(layer, "data") and layer.data is not None:
---> 57                 yield layer, self.subset(layer.data, **self._kwargs)
     58 
     59 

/home/kotfic/kitware/review/geonotebook/vector-dataset/geonotebook/annotations.py in subset(self, raster_data, **kwargs)
     71 
     72     def subset(self, raster_data, **kwargs):
---> 73         ul = raster_data.index(self.bounds[0], self.bounds[1])
     74         lr = raster_data.index(self.bounds[2], self.bounds[3])
     75         window = self.get_data_window(ul[0], ul[1], lr[0], lr[1])

TypeError: index() takes exactly 2 arguments (3 given)
```
 
Polygons and point also crash.  Ideally the annotation iterator would return polygon intersections,  but for this PR let's just tweak it to skip VectorLayers entirely.

**Comment by kotfic** [comment]
After adding a rectangle annotation (either through ```M.add_annotation(...)``` or the interface) - the following raises an Error:

```python
M.layers.annotation.rectangles[0]
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/kotfic/kitware/review/geonotebook/.vector-dataset/lib/python2.7/site-packages/IPython/core/formatters.pyc in __call__(self, obj)
    309             method = get_real_method(obj, self.print_method)
    310             if method is not None:
--> 311                 return method()
    312             return None
    313         else:

/home/kotfic/kitware/review/geonotebook/.vector-dataset/lib/python2.7/site-packages/shapely/geometry/base.pyc in _repr_svg_(self)
    405                 '<g transform="{3}">{4}</g></svg>'
    406                 ).format(view_box, width, height, transform,
--> 407                          self.svg(scale_factor))
    408 
    409     @property

/home/kotfic/kitware/review/geonotebook/vector-dataset/geonotebook/annotations.py in svg(self, *args, **kwargs)
     24     def svg(self, *args, **kwargs):
     25         if hasattr(super(Annotation, self), 'svg'):
---> 26             kwargs['fill_color'] = self.style['fillColor']
     27             return super(Annotation, self).svg(*args, **kwargs)
     28 

AttributeError: 'Rectangle' object has no attribute 'style'
```

Looks like I missed this on the Annotation PR review - [this](https://github.com/OpenGeoscience/geonotebook/blob/master/js/src/MapObject.js#L199-L203) seems to be changing the expected response which i believe were including key-value pairs like [fillColor](https://github.com/OpenGeoscience/geonotebook/blob/master/js/src/MapObject.js#L131-L133).

**Comment by jbeezley** [comment]
@kotfic PTAL, I think I fixed the issues you found.  As mentioned in person, the second issue above is likely due to a `.pyc` file sticking around from an old install.  The new integration test exercises the subsetting code.

**Pull request merged**
