### PR TITLE
Update Dockerfile to run on binder.

### PR DESCRIPTION
**Pull request by Carreau**
Remove running as root, set a jovyan user, and update a few other
related configurations.

Here is some extra information when [providing your own dockerfile](http://mybinder.readthedocs.io/en/latest/dockerfile.html)

You can try on https://mybinder.org/v2/gh/carreau/geonotebook/master (my fork)

### CODE REVIEW

**Comment by jbeezley** [comment]
Thanks for doing the leg work on this.  We had attempted a binder deployment before.  I believe we were blocked (in part) by #113.  As a result, we have to hard code the URL of the embedded tile server.  You can see the issue when trying to run the builtin raster example.  It throws an error when trying to add the raster data object to the map.

**Comment by aashish24** [comment]
@Carreau thanks for the PR. As we discussed earlier, I was hoping to use it for the workshop but as @jbeezley mentioned, the raster data example does not work because of the tile server url. Other basic examples are working fine.

**Comment by Carreau** [comment]
Hum, you can likely use something like https://github.com/jupyterhub/nbserverproxy to fix this issue. I'll have to dig deeper into this though. It redirects traffic from a given URL to another service running on the same container.

This should allow you to set `ktile_url` to something like `/ktile/` I doubt I can do that in 30 min though.

**Comment by aashish24** [comment]
@Carreau sure. Is there any chance you could look into it further?

**Pull request closed without merging**
